apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-bff-deployment-v1
  labels:
    app: order-bff-deployment
    version: v1
spec:
  selector:
    matchLabels:
      app: order-bff-deployment
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: order-bff-deployment
        version: v1
    spec:
      containers:
      - name: order-bff-deployment
        image: order-bff-server:0.2
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-bff-deployment-v2
  labels:
    app: order-bff-deployment
    version: v2
spec:
  selector:
    matchLabels:
      app: order-bff-deployment
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: order-bff-deployment
        version: v2
    spec:
      containers:
        - name: order-bff-deployment
          image: order-bff-server:0.2
          ports:
            - containerPort: 8080

