apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  selector:
    matchLabels:
      app: order-deployment
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: order-deployment
        version: v1
    spec:
      containers:
      - name: order-deployment
        image: order-server:0.3
        ports:
        - containerPort: 50050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment-v2
spec:
  selector:
    matchLabels:
      app: order-deployment
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: order-deployment
        version: v2
    spec:
      containers:
        - name: order-deployment
          image: order-server:0.3
          ports:
            - containerPort: 50050